# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/attendance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/attendance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/attendance.proto\x12\nattendance\"V\n\x10\x41ttendanceRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65mployee_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"/\n\x0bListRequest\x12\x13\n\x0b\x65mployee_id\x18\x01 \x01(\t\x12\x0b\n\x03jwt\x18\x02 \x01(\t\"\x1c\n\rStreamRequest\x12\x0b\n\x03jwt\x18\x01 \x01(\t2\x9c\x01\n\x11\x41ttendanceService\x12?\n\x04List\x12\x17.attendance.ListRequest\x1a\x1c.attendance.AttendanceRecord0\x01\x12\x46\n\tStreamNew\x12\x19.attendance.StreamRequest\x1a\x1c.attendance.AttendanceRecord0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.attendance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTENDANCERECORD']._serialized_start=38
  _globals['_ATTENDANCERECORD']._serialized_end=124
  _globals['_LISTREQUEST']._serialized_start=126
  _globals['_LISTREQUEST']._serialized_end=173
  _globals['_STREAMREQUEST']._serialized_start=175
  _globals['_STREAMREQUEST']._serialized_end=203
  _globals['_ATTENDANCESERVICE']._serialized_start=206
  _globals['_ATTENDANCESERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
